# Generated by Django 6.1.1 on 2026-09-18 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SELLER', 'Seller'), ('BUYER', 'Buyer'), ('PROPERTY', 'Property'), ('VEHICLE', 'Vehicle'), ('BUSINESS', 'Business')], max_length=20, verbose_name='Aina ya uthibitisho')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Hali')),
                ('user_name', models.CharField(blank=True, max_length=150, verbose_name='Jina la mtumiaji')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='Barua pepe ya mtumiaji')),
                ('subject', models.CharField(max_length=255, verbose_name='Kichwa')),
                ('subject_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID ya kitu')),
                ('notes', models.TextField(blank=True, verbose_name='Maelezo')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ilirekebishwa')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Sababu ya kukataa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Ilirekebishwa na')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL, verbose_name='Mtumiaji')),
            ],
            options={
                'verbose_name': 'Ombi la uthibitisho',
                'verbose_name_plural': 'Maombi ya uthibitisho',
                'db_table': 'verification_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='verifications/', verbose_name='Faili')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Jina la faili')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verifications.verificationrequest', verbose_name='Ombi')),
            ],
            options={
                'verbose_name': 'Nyaraka ya uthibitisho',
                'verbose_name_plural': 'Nyaraka za uthibitisho',
                'db_table': 'verification_documents',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['status', 'created_at'], name='vreq_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['type', 'status'], name='vreq_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['user'], name='vreq_user_idx'),
        ),
    ]
