# Generated by Django 6.1.1 on 2026-10-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0002_alter_verificationrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='documents_request_message',
            field=models.TextField(blank=True, default='', verbose_name='Message from admin'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='documents_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Documents requested at'),
        ),
    ]
