# Generated by Django 6.1.1 on 2026-09-18 22:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadingFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('10000'), max_digits=15)),
                ('days', models.PositiveIntegerField(default=7)),
                ('label_sw', models.CharField(default='Ada ya Kipaumbele', max_length=100)),
                ('label_en', models.CharField(default='Leading Fee', max_length=100)),
                ('desc_sw', models.TextField(default='Bidhaa yako inapanda juu ya matokeo ya utafutaji kwa siku 7')),
                ('desc_en', models.TextField(default='Your listing appears at the top of search results for 7 days')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ada ya Kipaumbele',
                'verbose_name_plural': 'Ada ya Kipaumbele',
                'db_table': 'leading_fee_config',
            },
        ),
    ]
