# Generated by Django 6.1.1 on 2026-09-28 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leading_fees', '0001_initial'),
        ('listings', '0013_alter_listing_seller_alter_listingfee_listing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingLeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(default=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leading_purchases', to='listings.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leading_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listing_leadings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', 'status'], name='leading_listing_status_idx'), models.Index(fields=['status', 'expires_at'], name='leading_status_exp_idx'), models.Index(fields=['seller', 'status'], name='leading_seller_status_idx')],
            },
        ),
    ]
