# Generated by Django 6.1.1 on 2026-10-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leading_fees', '0002_listingleading'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadingfeeconfig',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Kama False, leading haitozwi.'),
        ),
    ]
