# Generated by Django 6.1.1 on 2026-10-08 16:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leading_fees", "0003_add_is_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadingfeeconfig",
            name="days",
        ),
        migrations.RemoveField(
            model_name="leadingfeeconfig",
            name="price",
        ),
        migrations.AlterField(
            model_name="leadingfeeconfig",
            name="desc_en",
            field=models.TextField(
                default="Your listing appears at the top of search results"
            ),
        ),
        migrations.AlterField(
            model_name="leadingfeeconfig",
            name="desc_sw",
            field=models.TextField(
                default="Bidhaa yako inapanda juu ya matokeo ya utafutaji"
            ),
        ),
        migrations.AlterField(
            model_name="leadingfeeconfig",
            name="is_enabled",
            field=models.BooleanField(
                default=True, help_text="Kama False, leading haitozwi (ni bure)."
            ),
        ),
        migrations.AlterField(
            model_name="listingleading",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name="LeadingPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Mfano: Starter, Standard, Premium", max_length=100
                    ),
                ),
                (
                    "duration_hours",
                    models.PositiveIntegerField(
                        help_text="Muda wa leading kwa saa (24 = siku 1).",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Bei kwa TZS.",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Maelezo ya ziada (optional)."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Leading Package",
                "verbose_name_plural": "Leading Packages",
                "db_table": "leading_packages",
                "ordering": ["ordering", "duration_hours", "price"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "ordering"],
                        name="lead_pkg_active_order_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="unique_leading_package_name"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="listingleading",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listing_leadings",
                to="leading_fees.leadingpackage",
            ),
        ),
    ]
