# Generated by Django 6.1.1 on 2026-09-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=254, verbose_name='Email au namba ya simu')),
                ('verification_type', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone')], max_length=10, verbose_name='Aina ya uthibitishaji')),
                ('otp_code', models.CharField(max_length=6, verbose_name='OTP')),
                ('is_used', models.BooleanField(default=False, verbose_name='Imetumika')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Idadi ya majaribio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('expires_at', models.DateTimeField(verbose_name='Inaisha')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Imethibitishwa')),
            ],
            options={
                'verbose_name': 'Uthibitishaji wa OTP',
                'verbose_name_plural': 'Uthibitishaji wa OTP',
                'db_table': 'otp_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['identifier', 'verification_type', 'is_used'], name='otp_identifier_type_used_idx')],
            },
        ),
    ]
