# Generated by Django 6.1.1 on 2026-09-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otpverification_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Jina kamili')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Barua pepe')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Namba ya simu')),
                ('account_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business')], default='INDIVIDUAL', max_length=20, verbose_name='Aina ya akaunti')),
                ('password_hash', models.CharField(max_length=128, verbose_name='Hash ya nenosiri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
            ],
            options={
                'verbose_name': 'Usajili unaosubiri',
                'verbose_name_plural': 'Usajili unaosubiri',
                'db_table': 'pending_registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(help_text='OTP is stored as SHA-256 hash.', max_length=64, verbose_name='OTP'),
        ),
    ]
