# Generated by Django 6.1.1 on 2026-10-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="identifier",
            field=models.CharField(
                db_index=True, max_length=254, verbose_name="Barua pepe"
            ),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="verification_type",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("PASSWORD_RESET_EMAIL", "Password Reset (Email)"),
                ],
                max_length=30,
                verbose_name="Aina ya uthibitishaji",
            ),
        ),
        migrations.AlterField(
            model_name="pendingregistration",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Barua pepe"
            ),
        ),
    ]
