# Generated by Django 6.1.1 on 2026-10-08 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_otpverification_identifier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_deals", models.BooleanField(default=True)),
                ("email_messages", models.BooleanField(default=True)),
                ("email_promotions", models.BooleanField(default=False)),
                ("email_newsletter", models.BooleanField(default=True)),
                ("sms_deals", models.BooleanField(default=True)),
                ("sms_messages", models.BooleanField(default=False)),
                ("sms_promotions", models.BooleanField(default=False)),
                ("push_deals", models.BooleanField(default=True)),
                ("push_messages", models.BooleanField(default=True)),
                ("push_promotions", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "user_notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("sw", "Kiswahili"), ("en", "English")],
                        default="sw",
                        max_length=5,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("TZS", "Tanzanian Shilling"), ("USD", "US Dollar")],
                        default="TZS",
                        max_length=5,
                    ),
                ),
                ("region", models.CharField(default="Dar es Salaam", max_length=100)),
                ("show_phone", models.BooleanField(default=True)),
                ("show_email", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preferences",
                "verbose_name_plural": "User Preferences",
                "db_table": "user_preferences",
            },
        ),
    ]
