# Generated by Django 6.1.1 on 2026-10-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_notificationpreference_userpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
