services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/media
    env_file:
      - .env
    environment:
      DEBUG: "False"
    ports:
      - "8000:8000"

volumes:
  static_files:
  media_files:
