# Generated by Django 6.1.1 on 2026-09-18 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0009_listingfee_percentage_listingfee_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message', models.TextField(blank=True, verbose_name='Ujumbe wa mwisho')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Muda wa ujumbe wa mwisho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Mnunuzi')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='listings.listing', verbose_name='Tangazo')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Muuzaji')),
            ],
            options={
                'verbose_name': 'Mazungumzo',
                'verbose_name_plural': 'Mazungumzo',
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['buyer', 'updated_at'], name='conv_buyer_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['seller', 'updated_at'], name='conv_seller_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('listing', 'buyer', 'seller'), name='unique_conversation_triple'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='msg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read'], name='msg_conv_read_idx'),
        ),
    ]
