# Generated by Django 6.1.1 on 2026-09-18 22:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('25000'), max_digits=15)),
                ('days', models.PositiveIntegerField(default=7)),
                ('label_sw', models.CharField(default='Ada ya Matangazo', max_length=100)),
                ('label_en', models.CharField(default='Advertisement Fee', max_length=100)),
                ('desc_sw', models.TextField(default='Banner inayozunguka kwenye Dashboard (5s rotation) kwa siku 7')),
                ('desc_en', models.TextField(default='Rotating banner on the Dashboard (5s rotation) for 7 days')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ada ya Matangazo',
                'verbose_name_plural': 'Ada ya Matangazo',
                'db_table': 'advertisement_fee_config',
            },
        ),
    ]
