# Generated by Django 6.1.1 on 2026-10-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementfeeconfig',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Kama False, matangazo hayatozwi.'),
        ),
    ]
