# Generated by Django 6.1.1 on 2026-10-08 16:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement_fees", "0002_add_is_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisementfeeconfig",
            name="days",
        ),
        migrations.RemoveField(
            model_name="advertisementfeeconfig",
            name="price",
        ),
        migrations.AlterField(
            model_name="advertisementfeeconfig",
            name="desc_en",
            field=models.TextField(
                default="Rotating banner on the Dashboard for 7 days"
            ),
        ),
        migrations.AlterField(
            model_name="advertisementfeeconfig",
            name="desc_sw",
            field=models.TextField(
                default="Banner inayozunguka kwenye Dashboard kwa siku 7"
            ),
        ),
        migrations.AlterField(
            model_name="advertisementfeeconfig",
            name="is_enabled",
            field=models.BooleanField(
                default=True, help_text="Kama False, matangazo hayatozwi (ni bure)."
            ),
        ),
        migrations.CreateModel(
            name="AdvertisementPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Mfano: Starter, Standard, Premium", max_length=100
                    ),
                ),
                (
                    "duration_hours",
                    models.PositiveIntegerField(
                        help_text="Muda wa tangazo kwa saa (24 = siku 1).",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Bei kwa TZS.",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Maelezo ya ziada (optional)."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Advertisement Package",
                "verbose_name_plural": "Advertisement Packages",
                "db_table": "advertisement_packages",
                "ordering": ["ordering", "duration_hours", "price"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "ordering"], name="ad_pkg_active_order_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="unique_advertisement_package_name"
                    )
                ],
            },
        ),
    ]
