# Generated by Django 6.1.1 on 2026-09-10 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0007_alter_listingfeerule_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('NOTIFIED', 'Notified'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled')], default='WAITING', max_length=20, verbose_name='Hali')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Nafasi')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kutaarifiwa')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Muda wa kujiunga')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to=settings.AUTH_USER_MODEL, verbose_name='Mnunuzi')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to='listings.listing', verbose_name='Tangazo')),
            ],
            options={
                'db_table': 'waiting_list_entries',
                'ordering': ['position', 'joined_at'],
                'indexes': [models.Index(fields=['listing', 'status', 'position'], name='wait_listing_status_pos_idx'), models.Index(fields=['buyer', 'status'], name='wait_buyer_status_idx'), models.Index(fields=['status', 'joined_at'], name='wait_status_joined_idx')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'buyer'), name='unique_waiting_listing_buyer')],
            },
        ),
    ]
