# Generated by Django 6.1.1 on 2026-09-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='waitinglistentry',
            name='unique_waiting_listing_buyer',
        ),
    ]
