# Generated by Django 6.1.1 on 2026-09-27 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_re_add_leading_until'),
        ('waiting_list', '0002_remove_waitinglistentry_unique_waiting_listing_buyer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='waitinglistentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['WAITING', 'NOTIFIED'])), fields=('listing', 'buyer'), name='unique_active_waiting_entry'),
        ),
    ]
