# Generated by Django 6.1.1 on 2026-09-18 22:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('LISTING', 'Listing'), ('LEADING', 'Leading'), ('BOOST', 'Boost'), ('RESERVATION', 'Reservation'), ('ADS', 'Ads'), ('PREMIUM', 'Premium'), ('PACKAGE', 'Package')], max_length=20, verbose_name='Aina')),
                ('name_sw', models.CharField(max_length=150, verbose_name='Jina (SW)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='Jina (EN)')),
                ('description_sw', models.TextField(blank=True, verbose_name='Maelezo (SW)')),
                ('description_en', models.TextField(blank=True, verbose_name='Maelezo (EN)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Bei')),
                ('credits', models.JSONField(blank=True, default=dict, verbose_name='Credits')),
                ('validity_days', models.PositiveIntegerField(default=90, verbose_name='Siku za uhalali')),
                ('services', models.JSONField(blank=True, default=list, verbose_name='Huduma')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Punguzo (%)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Rangi')),
                ('active', models.BooleanField(default=True, verbose_name='Hai')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Mpangilio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kifurushi',
                'verbose_name_plural': 'Vifurushi',
                'db_table': 'bundles',
                'ordering': ['ordering', 'price'],
                'indexes': [models.Index(fields=['active', 'ordering'], name='bundle_active_order_idx'), models.Index(fields=['type', 'active'], name='bundle_type_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='BundlePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kiasi')),
                ('credits_snapshot', models.JSONField(blank=True, default=dict)),
                ('services_snapshot', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='Hali')),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Payment reference')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='bundles.bundle', verbose_name='Kifurushi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Mtumiaji')),
            ],
            options={
                'verbose_name': 'Ununuzi wa kifurushi',
                'verbose_name_plural': 'Manunuzi ya vifurushi',
                'db_table': 'bundle_purchases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='bpurchase_user_status_idx'), models.Index(fields=['status', 'created_at'], name='bpurchase_status_created_idx')],
            },
        ),
    ]
