# Generated by Django 6.1.1 on 2026-10-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0002_bundlepurchase_uniq_pending_purchase_per_user_bundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='type',
            field=models.CharField(choices=[('LISTING', 'Listing'), ('LEADING', 'Leading'), ('BOOST', 'Boost'), ('RESERVATION', 'Reservation'), ('SUCCESS', 'Success'), ('ADS', 'Ads'), ('PREMIUM', 'Premium'), ('PACKAGE', 'Package')], max_length=20, verbose_name='Aina'),
        ),
    ]
