# Generated by Django 6.1.1 on 2026-09-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Jina la kundi')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Lipo hai')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Namba ndogo huonekana kwanza.', verbose_name='Mpangilio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
            ],
            options={
                'verbose_name': 'Kundi',
                'verbose_name_plural': 'Makundi',
                'db_table': 'categories',
                'ordering': ['ordering', 'name'],
            },
        ),
    ]
