# Generated by Django 6.1.1 on 2026-09-27 23:51

import apps.core.managers
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('categories', '0001_initial'), ('categories', '0002_alter_category_options_alter_category_managers_and_more'), ('categories', '0003_remove_category_unique_active_category_name_and_more'), ('categories', '0004_category_extra_fields'), ('categories', '0005_alter_category_managers_remove_category_extra_and_more'), ('categories', '0006_category_extra_fields_restore')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jina la kundi')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Lipo hai')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Namba ndogo huonekana kwanza.', verbose_name='Mpangilio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deletion_reason', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Data ya ziada')),
                ('icon_key', models.CharField(blank=True, help_text='Mfano: home, car, briefcase', max_length=50, verbose_name='Ufunguo wa icon')),
                ('image_url', models.URLField(blank=True, verbose_name='URL ya picha')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Maarufu')),
            ],
            options={
                'verbose_name': 'Kundi',
                'verbose_name_plural': 'Makundi',
                'db_table': 'categories',
                'ordering': ['ordering', 'name'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('slug',), name='unique_active_category_slug'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_deleted', False)), name='unique_active_category_name')],
            },
            managers=[
                ('objects', apps.core.managers.SoftDeleteManager()),
                ('all_objects', apps.core.managers.SoftDeleteManager(include_deleted=True)),
            ],
        ),
    ]
