# Generated by Django 6.1.1 on 2026-09-20 15:32

import apps.core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_extra_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('objects', apps.core.managers.SoftDeleteManager()),
                ('all_objects', apps.core.managers.SoftDeleteManager(include_deleted=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon_key',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_popular',
        ),
    ]
