# Generated by Django 6.1.1 on 2026-09-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_managers_remove_category_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='Data ya ziada'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_key',
            field=models.CharField(blank=True, help_text='Mfano: home, car, briefcase', max_length=50, verbose_name='Ufunguo wa icon'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='URL ya picha'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Maarufu'),
        ),
    ]
