# Generated by Django 6.1.1 on 2026-09-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_category_extra_fields_restore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='URL ya picha'),
        ),
    ]
