# Generated by Django 6.1.1 on 2026-09-18 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FEE_CHANGE', 'Fee Change'), ('NEW_CATEGORY', 'New Category'), ('MAINTENANCE', 'System Maintenance'), ('PROMOTION', 'Campaign/Promotion')], default='MAINTENANCE', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('message_en', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sent', 'created_at'], name='ann_sent_created_idx')],
            },
        ),
    ]
