# Generated by Django 6.1.1 on 2026-10-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=50, unique=True, verbose_name='Ufunguo')),
                ('label_sw', models.CharField(default='Ada ya Mafanikio', max_length=100, verbose_name='Jina (Kiswahili)')),
                ('label_en', models.CharField(blank=True, default='Success Fee', max_length=100, verbose_name='Jina (Kiingereza)')),
                ('desc_sw', models.TextField(blank=True, default='Ada ndogo ya kupakua ripoti ya miamala.', verbose_name='Maelezo (Kiswahili)')),
                ('desc_en', models.TextField(blank=True, default='Small fee to download transactions report.', verbose_name='Maelezo (Kiingereza)')),
                ('percentage', models.DecimalField(decimal_places=2, default=2.0, help_text='Asilimia ya deal, mfano 2.0 kwa 2%.', max_digits=5, verbose_name='Asilimia')),
                ('min_fee', models.DecimalField(decimal_places=2, default=5000, help_text='Ada ya chini — pia flat fee kwa CSV/PDF download.', max_digits=12, verbose_name='Ada ya Chini (TZS)')),
                ('max_fee', models.DecimalField(decimal_places=2, default=500000, max_digits=12, verbose_name='Ada ya Juu (TZS)')),
                ('is_enabled', models.BooleanField(default=True, help_text='Kama False, hakuna ada ya mafanikio na download ni bure.', verbose_name='Inatumika')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ada ya Mafanikio',
                'verbose_name_plural': 'Ada ya Mafanikio',
                'db_table': 'success_fee_config',
            },
        ),
        migrations.CreateModel(
            name='SystemFeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ufunguo')),
                ('label_sw', models.CharField(max_length=100, verbose_name='Jina (Kiswahili)')),
                ('label_en', models.CharField(blank=True, max_length=100, verbose_name='Jina (Kiingereza)')),
                ('desc_sw', models.TextField(blank=True, verbose_name='Maelezo (Kiswahili)')),
                ('desc_en', models.TextField(blank=True, verbose_name='Maelezo (Kiingereza)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Inatumika')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kipengele cha Mfumo',
                'verbose_name_plural': 'Vipengele vya Mfumo',
                'db_table': 'system_feature_toggles',
                'ordering': ['key'],
            },
        ),
    ]
