# Generated by Django 6.1.1 on 2026-09-10 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('GENERAL', 'General'), ('LISTING_CREATED', 'Listing Created'), ('LISTING_APPROVED', 'Listing Approved'), ('LISTING_REJECTED', 'Listing Rejected'), ('NEW_OFFER', 'New Offer'), ('OFFER_COUNTERED', 'Offer Countered'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('TRANSACTION_CREATED', 'Transaction Created'), ('RESERVATION_CREATED', 'Reservation Created'), ('RESERVATION_PAID', 'Reservation Paid'), ('RESERVATION_EXPIRING', 'Reservation Expiring'), ('RESERVATION_EXPIRED', 'Reservation Expired'), ('INSPECTION_STARTED', 'Inspection Started'), ('INSPECTION_COMPLETED', 'Inspection Completed'), ('BUYER_DECISION', 'Buyer Decision'), ('PAYMENT_PROOF_UPLOADED', 'Payment Proof Uploaded'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('TRANSACTION_COMPLETED', 'Transaction Completed'), ('TRANSACTION_CANCELLED', 'Transaction Cancelled'), ('WAITING_LIST_JOINED', 'Waiting List Joined'), ('WAITING_LIST_AVAILABLE', 'Waiting List Available'), ('BOOST_ACTIVATED', 'Boost Activated')], default='GENERAL', max_length=50, verbose_name='Aina ya arifa')),
                ('title', models.CharField(max_length=255, verbose_name='Kichwa')),
                ('message', models.TextField(verbose_name='Ujumbe')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20, verbose_name='Kipaumbele')),
                ('is_read', models.BooleanField(default=False, verbose_name='Imesomwa')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kusomwa')),
                ('related_object_type', models.CharField(blank=True, max_length=100, verbose_name='Aina ya kitu kinachohusiana')),
                ('related_object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID ya kitu kinachohusiana')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Kiungo cha hatua')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Mpokeaji')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notif_recipient_read_idx'), models.Index(fields=['recipient', 'notification_type'], name='notif_recipient_type_idx'), models.Index(fields=['priority', 'created_at'], name='notif_priority_created_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='notif_related_obj_idx')],
            },
        ),
    ]
