# Generated by Django 6.1.1 on 2026-09-18 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        ('listings', '0009_listingfee_percentage_listingfee_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=150, verbose_name='Jina la mnunuzi')),
                ('message', models.TextField(blank=True, verbose_name='Ujumbe')),
                ('source', models.CharField(choices=[('MESSAGE', 'Message'), ('DEAL', 'Deal Room')], default='DEAL', max_length=20, verbose_name='Chanzo')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('RESPONDED', 'Responded'), ('CONVERTED', 'Converted'), ('IGNORED', 'Ignored')], default='NEW', max_length=20, verbose_name='Hali')),
                ('message_count', models.PositiveIntegerField(default=1, verbose_name='Idadi ya ujumbe')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kujibu')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kubadilisha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_leads', to=settings.AUTH_USER_MODEL, verbose_name='Mnunuzi')),
                ('deal_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='deals.dealroom', verbose_name='Deal Room')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='listings.listing', verbose_name='Tangazo')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_leads', to=settings.AUTH_USER_MODEL, verbose_name='Muuzaji')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', 'status'], name='lead_seller_status_idx'), models.Index(fields=['listing', 'created_at'], name='lead_listing_created_idx'), models.Index(fields=['buyer'], name='lead_buyer_idx')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'buyer'), name='unique_lead_listing_buyer')],
            },
        ),
    ]
