# Generated by Django 6.1.1 on 2026-09-27 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('listings', '0012_re_add_leading_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_leads', to=settings.AUTH_USER_MODEL, verbose_name='Mnunuzi'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='listings.listing', verbose_name='Tangazo'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_leads', to=settings.AUTH_USER_MODEL, verbose_name='Muuzaji'),
        ),
    ]
