# Generated by Django 6.1.1 on 2026-09-27 23:21

import apps.core.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_buyer_alter_lead_listing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelManagers(
            name='lead',
            managers=[
                ('objects', apps.core.managers.SoftDeleteManager()),
                ('all_objects', apps.core.managers.SoftDeleteManager(include_deleted=True)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
