# Generated by Django 6.1.1 on 2026-10-04 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_remove_dealroom_unique_deal_room_listing_buyer_and_more'),
        ('leads', '0003_alter_lead_options_alter_lead_managers_and_more'),
        ('listings', '0016_listingfeerule_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lead',
            name='unique_lead_listing_buyer',
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('listing', 'buyer'), name='unique_active_lead_listing_buyer'),
        ),
    ]
