http:
  routers:
    sokomkononi-api-router:
      rule: "Host(`api.sokomkononi.co.tz`)"
      service: "sokomkononi-api-service"
      entryPoints:
        - web
        - websecure
      middlewares:
        - redirect-to-https
      tls:
        certResolver: "letsencrypt"

  services:
    sokomkononi-api-service:
      loadBalancer:
        servers:
          # Choose ONE of these two lines:
          # - url: "http://web:8000"          # if Traefik and web share a Docker network
          - url: "http://172.17.0.1:8000"     # if Traefik runs on the host