http:
  routers:
    sokomkononi-frontend-router:
      rule: "Host(`www.sokomkononi.co.tz`) || Host(`sokomkononi.co.tz`)"
      service: "sokomkononi-frontend-service"
      entryPoints:
        - web
        - websecure
      middlewares:
        - redirect-to-https
      tls:
        certResolver: "letsencrypt"

  services:
    sokomkononi-frontend-service:
      loadBalancer:
        servers:
          - url: "http://10.0.1.17:3001"