# Generated by Django 6.1.1 on 2026-09-29 14:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Withdrawal ID (FimiPay)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kiasi kilichoombwa')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ada')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Kiasi halisi')),
                ('method', models.CharField(max_length=100, verbose_name='Njia (M-Pesa / CRDB Bank / ...)')),
                ('account_number', models.CharField(max_length=64, verbose_name='Namba ya akaunti')),
                ('account_name', models.CharField(blank=True, max_length=150, verbose_name='Jina la akaunti')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Hali')),
                ('fimi_status', models.CharField(blank=True, max_length=30, verbose_name='Hali ya FimiPay (raw)')),
                ('failure_reason', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fimipay_payouts', to=settings.AUTH_USER_MODEL, verbose_name='Iliundwa na')),
            ],
            options={
                'verbose_name': 'Malipo ya kutoka (payout)',
                'verbose_name_plural': 'Malipo ya kutoka (payouts)',
                'db_table': 'fimipay_payouts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payout_status_created_idx'), models.Index(fields=['created_by', 'status'], name='payout_user_status_idx')],
            },
        ),
    ]
