# Generated by Django 6.1.1 on 2026-09-18 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dispute_resolution_note',
            field=models.TextField(blank=True, verbose_name='Maelezo ya uamuzi wa mgogoro'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dispute_resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL, verbose_name='Mgogoro umetatuliwa na'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESERVATION_PENDING', 'Reservation Pending'), ('RESERVED', 'Reserved'), ('INSPECTION', 'Inspection'), ('READY_FOR_FINAL_PAYMENT', 'Ready for Final Payment'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], default='RESERVATION_PENDING', max_length=30, verbose_name='Hali ya muamala'),
        ),
    ]
