# Generated by Django 6.1.1 on 2026-10-06 05:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_dispute_resolution_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kiasi cha deposit'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Payment reference'),
        ),
    ]
