# Generated by Django 6.1.1 on 2026-10-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_reservation_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['payment_reference'], name='res_payment_ref_idx'),
        ),
    ]
