# Generated by Django 6.1.1 on 2026-09-27 23:21

import apps.core.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
                ('objects', apps.core.managers.SoftDeleteManager()),
                ('all_objects', apps.core.managers.SoftDeleteManager(include_deleted=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
