# Generated by Django 6.1.1 on 2026-10-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_options_alter_ticket_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('COMPLETED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
