# Generated by Django 6.1.1 on 2026-09-09 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Jina la mali')),
                ('description', models.TextField(verbose_name='Maelezo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Bei')),
                ('location', models.CharField(max_length=255, verbose_name='Mahali')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30, verbose_name='Hali')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Imewekwa kwenye featured')),
                ('is_boosted', models.BooleanField(default=False, verbose_name='Imeboostiwa')),
                ('boosted_until', models.DateTimeField(blank=True, null=True, verbose_name='Boost inaisha')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Idadi ya kutazamwa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='categories.category', verbose_name='Kundi')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Muuzaji')),
            ],
            options={
                'verbose_name': 'Tangazo',
                'verbose_name_plural': 'Matangazo',
                'db_table': 'listings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'status'], name='listing_category_status_idx'), models.Index(fields=['seller', 'status'], name='listing_seller_status_idx'), models.Index(fields=['status', 'created_at'], name='listing_status_created_idx')],
            },
        ),
    ]
