# Generated by Django 6.1.1 on 2026-09-09 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/', verbose_name='Picha')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ni picha kuu')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Mpangilio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing', verbose_name='Tangazo')),
            ],
            options={
                'verbose_name': 'Picha ya tangazo',
                'verbose_name_plural': 'Picha za matangazo',
                'db_table': 'listing_images',
                'ordering': ['ordering', 'created_at'],
                'indexes': [models.Index(fields=['listing', 'is_primary'], name='listing_image_primary_idx')],
            },
        ),
    ]
