# Generated by Django 6.1.1 on 2026-09-09 23:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bei'),
        ),
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=100, verbose_name='Aina ya biashara')),
                ('years_operating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Miaka ya biashara')),
                ('number_of_employees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idadi ya wafanyakazi')),
                ('monthly_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mapato ya mwezi')),
                ('monthly_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gharama za mwezi')),
                ('has_business_license', models.BooleanField(default=False, verbose_name='Ina leseni ya biashara')),
                ('has_tin', models.BooleanField(default=False, verbose_name='Ina TIN')),
                ('premises_included', models.BooleanField(default=False, verbose_name='Eneo la biashara linajumuishwa')),
                ('stock_included', models.BooleanField(default=False, verbose_name='Stock inajumuishwa')),
                ('reason_for_sale', models.TextField(blank=True, verbose_name='Sababu ya kuuza')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_details', to='listings.listing', verbose_name='Tangazo')),
            ],
            options={
                'verbose_name': 'Maelezo ya biashara',
                'verbose_name_plural': 'Maelezo ya biashara',
                'db_table': 'business_details',
            },
        ),
        migrations.CreateModel(
            name='EquipmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=100, verbose_name='Aina ya mashine')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Manufacturer')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mwaka')),
                ('condition', models.CharField(choices=[('NEW', 'Mpya'), ('USED', 'Imetumika'), ('REFURBISHED', 'Imerekebishwa')], max_length=20, verbose_name='Hali ya mashine')),
                ('operating_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Masaa ya matumizi')),
                ('fuel_type', models.CharField(blank=True, max_length=50, verbose_name='Aina ya mafuta')),
                ('engine_capacity', models.CharField(blank=True, max_length=50, verbose_name='Engine capacity')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Uzito (kg)')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial number')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='Nchi ilikotoka')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_details', to='listings.listing', verbose_name='Tangazo')),
            ],
            options={
                'verbose_name': 'Maelezo ya mashine',
                'verbose_name_plural': 'Maelezo ya mashine',
                'db_table': 'equipment_details',
            },
        ),
        migrations.CreateModel(
            name='LandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_type', models.CharField(choices=[('PLOT', 'Kiwanja'), ('FARM', 'Shamba'), ('AGRICULTURAL', 'Ardhi ya kilimo'), ('COMMERCIAL', 'Ardhi ya biashara'), ('RESIDENTIAL', 'Ardhi ya makazi'), ('OTHER', 'Nyingine')], max_length=30, verbose_name='Aina ya ardhi')),
                ('size', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ukubwa')),
                ('size_unit', models.CharField(choices=[('SQM', 'Mita za mraba'), ('ACRE', 'Ekari'), ('HECTARE', 'Hekta')], max_length=15, verbose_name='Kipimo cha ukubwa')),
                ('region', models.CharField(max_length=100, verbose_name='Mkoa')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Wilaya')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Kata')),
                ('village_or_street', models.CharField(blank=True, max_length=150, verbose_name='Kijiji/Mtaa')),
                ('title_document', models.CharField(blank=True, max_length=100, verbose_name='Aina ya hati')),
                ('surveyed', models.BooleanField(default=False, verbose_name='Imepimwa')),
                ('road_access', models.BooleanField(default=True, verbose_name='Ina njia ya barabara')),
                ('electricity_nearby', models.BooleanField(default=False, verbose_name='Umeme upo karibu')),
                ('water_nearby', models.BooleanField(default=False, verbose_name='Maji yapo karibu')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_details', to='listings.listing', verbose_name='Tangazo')),
            ],
            options={
                'verbose_name': 'Maelezo ya ardhi',
                'verbose_name_plural': 'Maelezo ya ardhi',
                'db_table': 'land_details',
            },
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('HOUSE', 'Nyumba'), ('APARTMENT', 'Apartment'), ('OFFICE', 'Ofisi'), ('SHOP', 'Duka'), ('WAREHOUSE', 'Ghala'), ('HOTEL', 'Hoteli'), ('OTHER', 'Nyingine')], max_length=30, verbose_name='Aina ya jengo')),
                ('bedrooms', models.PositiveSmallIntegerField(default=0, verbose_name='Vyumba vya kulala')),
                ('bathrooms', models.PositiveSmallIntegerField(default=0, verbose_name='Vyumba vya kuogea')),
                ('floors', models.PositiveSmallIntegerField(default=1, verbose_name='Idadi ya ghorofa')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ukubwa (m²)')),
                ('furnished', models.BooleanField(default=False, verbose_name='Ina samani')),
                ('has_electricity', models.BooleanField(default=True, verbose_name='Ina umeme')),
                ('has_water', models.BooleanField(default=True, verbose_name='Ina maji')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Ina maegesho')),
                ('ownership_document', models.CharField(blank=True, max_length=100, verbose_name='Aina ya hati ya umiliki')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_details', to='listings.listing', verbose_name='Tangazo')),
            ],
            options={
                'verbose_name': 'Maelezo ya nyumba/jengo',
                'verbose_name_plural': 'Maelezo ya nyumba/majengo',
                'db_table': 'property_details',
            },
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Manufacturer')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mwaka')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Gari'), ('SUV', 'SUV'), ('PICKUP', 'Pickup'), ('VAN', 'Van'), ('TRUCK', 'Lori'), ('BUS', 'Basi'), ('MOTORCYCLE', 'Pikipiki'), ('OTHER', 'Nyingine')], max_length=30, verbose_name='Aina ya gari')),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Electric'), ('OTHER', 'Nyingine')], max_length=20, verbose_name='Aina ya mafuta')),
                ('transmission', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual'), ('SEMI_AUTOMATIC', 'Semi-Automatic')], max_length=30, verbose_name='Transmission')),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mileage (km)')),
                ('engine_capacity_cc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Engine capacity (cc)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Rangi')),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Viti')),
                ('registration_number', models.CharField(blank=True, max_length=30, verbose_name='Namba ya usajili')),
                ('has_logbook', models.BooleanField(default=False, verbose_name='Ina logbook')),
                ('has_valid_insurance', models.BooleanField(default=False, verbose_name='Ina bima halali')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details', to='listings.listing', verbose_name='Tangazo')),
            ],
            options={
                'verbose_name': 'Maelezo ya gari',
                'verbose_name_plural': 'Maelezo ya magari',
                'db_table': 'vehicle_details',
            },
        ),
    ]
