# Generated by Django 6.1.1 on 2026-09-10 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_price_businessdetails_equipmentdetails_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kiasi cha ada')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Inasubiri Malipo'), ('PAID', 'Imelipwa'), ('FAILED', 'Imeshindikana'), ('REFUNDED', 'Imerejeshwa')], default='PENDING', max_length=20, verbose_name='Hali ya malipo')),
                ('payment_reference', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Namba ya kumbukumbu ya malipo')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Tarehe ya malipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing_fee', to='listings.listing', verbose_name='Tangazo')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_fees', to=settings.AUTH_USER_MODEL, verbose_name='Muuzaji')),
            ],
            options={
                'verbose_name': 'Ada ya tangazo',
                'verbose_name_plural': 'Ada za matangazo',
                'db_table': 'listing_fees',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', 'payment_status'], name='listing_fee_seller_status_idx'), models.Index(fields=['payment_status'], name='listing_fee_payment_status_idx')],
            },
        ),
    ]
