# Generated by Django 6.1.1 on 2026-09-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jina la kiwango')),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bei ya chini')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Acha wazi kwa kiwango kisicho na mwisho wa juu.', max_digits=15, null=True, verbose_name='Bei ya juu')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Mfano: 2.50 kwa 2.5%', max_digits=5, verbose_name='Asilimia ya ada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inatumika')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Namba ndogo hupewa kipaumbele cha kwanza.', verbose_name='Kipaumbele')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
