# Generated by Django 6.1.1 on 2026-09-10 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listingfeerule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingfee',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kuidhinishwa'),
        ),
        migrations.AddField(
            model_name='listingfee',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_listings', to=settings.AUTH_USER_MODEL, verbose_name='Imeidhinishwa na'),
        ),
        migrations.AddField(
            model_name='listingfee',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kukataliwa'),
        ),
        migrations.AddField(
            model_name='listingfee',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_listings', to=settings.AUTH_USER_MODEL, verbose_name='Imekataliwa na'),
        ),
        migrations.AddField(
            model_name='listingfee',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Sababu ya kukataliwa'),
        ),
    ]
