# Generated by Django 6.1.1 on 2026-09-10 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listingfee_approved_at_listingfee_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingfeerule',
            options={'ordering': ['priority', 'min_price'], 'verbose_name': 'Kanuni ya ada ya tangazo', 'verbose_name_plural': 'Kanuni za ada za matangazo'},
        ),
        migrations.RemoveField(
            model_name='listingfee',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='listingfee',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='listingfee',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='listingfee',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='listingfee',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='listing',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kuidhinishwa'),
        ),
        migrations.AddField(
            model_name='listing',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_listings', to=settings.AUTH_USER_MODEL, verbose_name='Imeidhinishwa na'),
        ),
        migrations.AddField(
            model_name='listing',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kukataliwa'),
        ),
        migrations.AddField(
            model_name='listing',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_listings', to=settings.AUTH_USER_MODEL, verbose_name='Imekataliwa na'),
        ),
        migrations.AddField(
            model_name='listing',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Sababu ya kukataliwa'),
        ),
        migrations.AddIndex(
            model_name='listingfeerule',
            index=models.Index(fields=['is_active', 'priority'], name='fee_rule_active_prio_idx'),
        ),
        migrations.AlterModelTable(
            name='listingfeerule',
            table='listing_fee_rules',
        ),
    ]
