# Generated by Django 6.1.1 on 2026-09-18 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_options_alter_listingfeerule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingfee',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Asilimia iliyotumika'),
        ),
        migrations.AddField(
            model_name='listingfee',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_fees', to='listings.listingfeerule', verbose_name='Kiwango kilichotumika'),
        ),
        migrations.AddConstraint(
            model_name='listingimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('listing',), name='unique_primary_image_per_listing'),
        ),
    ]
