# Generated by Django 6.1.1 on 2026-09-20 15:32

import apps.core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_leading_until'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listing',
            managers=[
                ('objects', apps.core.managers.SoftDeleteManager()),
                ('all_objects', apps.core.managers.SoftDeleteManager(include_deleted=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='listingfeerule',
            managers=[
                ('objects', apps.core.managers.SoftDeleteManager()),
                ('all_objects', apps.core.managers.SoftDeleteManager(include_deleted=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='leading_until',
        ),
    ]
