# Generated by Django 6.1.1 on 2026-09-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_listing_managers_alter_listingfeerule_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='leading_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Leading inaisha'),
        ),
    ]
