# Generated by Django 6.1.1 on 2026-09-28 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_re_add_leading_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Muuzaji'),
        ),
        migrations.AlterField(
            model_name='listingfee',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='listing_fee', to='listings.listing', verbose_name='Tangazo'),
        ),
        migrations.AlterField(
            model_name='listingfee',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_fees', to=settings.AUTH_USER_MODEL, verbose_name='Muuzaji'),
        ),
    ]
