# Generated by Django 6.1.1 on 2026-10-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_listing_seller_alter_listingfee_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingfeerule',
            name='fee_mode',
            field=models.CharField(choices=[('PERCENTAGE', 'Asilimia ya Bei'), ('FLAT', 'Flat Fee (TZS)')], default='PERCENTAGE', help_text='Chagua jinsi ada inavyokokotolewa.', max_length=10, verbose_name='Aina ya Ada'),
        ),
        migrations.AddField(
            model_name='listingfeerule',
            name='flat_fee',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Kama fee_mode = FLAT, ada hii inatumika.', max_digits=12, verbose_name='Flat Fee (TZS)'),
        ),
        migrations.AlterField(
            model_name='listingfeerule',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Mfano: 2.50 kwa 2.5%. Tumia 0 kama fee_mode = FLAT.', max_digits=5, verbose_name='Asilimia ya ada'),
        ),
    ]
