# Generated by Django 6.1.1 on 2026-10-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_add_fee_mode_flat_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Data ya category-specific: bedrooms, bathrooms, make, model, mileage, mode, region, district, area, n.k.', verbose_name='Sifa za ziada'),
        ),
    ]
