# Generated by Django 6.1.1 on 2026-10-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_listing_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingfeerule',
            name='category_slug',
            field=models.SlugField(blank=True, help_text='Slug ya Category ambayo rule hii inatumika (optional).', max_length=120, verbose_name='Slug ya kundi'),
        ),
    ]
