# Generated by Django 6.1.1 on 2026-10-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_widen_image_url'),
        ('listings', '0016_listingfeerule_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingfeerule',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category ambayo rule hii inatumika. Hii ni authoritative — inatumika kwanza kwenye lookup.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_rules', to='categories.category', verbose_name='Kundi'),
        ),
        migrations.AlterField(
            model_name='listingfeerule',
            name='category_slug',
            field=models.SlugField(blank=True, help_text='Fallback ya slug. Tumika tu kama `category` FK haipo.', max_length=120, verbose_name='Slug ya kundi (legacy)'),
        ),
    ]
