# Generated by Django 6.1.1 on 2026-10-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_listingfeerule_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending payment'), ('PENDING_APPROVAL', 'Pending approval'), ('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30, verbose_name='Hali'),
        ),
    ]
