# Generated by Django 6.1.1 on 2026-10-06 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_widen_image_url'),
        ('listings', '0019_rename_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending payment'), ('PENDING_APPROVAL', 'Pending approval'), ('LIVE', 'Live'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('PAUSED', 'Paused'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30, verbose_name='Hali'),
        ),
        migrations.AddConstraint(
            model_name='listingfeerule',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False), ('is_active', True), ('is_deleted', False)), fields=('category',), name='unique_active_rule_per_category'),
        ),
    ]
