# Generated by Django 5.1.15 on 2026-10-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_alter_listing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='card',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='listings/variants/', verbose_name='Card (WebP 400px)'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='detail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='listings/variants/', verbose_name='Detail (WebP 800px)'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='large',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='listings/variants/', verbose_name='Large (WebP 1200px)'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='listings/variants/', verbose_name='Thumb (WebP 200px)'),
        ),
    ]
