# Generated by Django 6.1.1 on 2026-10-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='location',
            field=models.CharField(blank=True, help_text='Mfano: Dar es Salaam, Mwanza, n.k.', max_length=150, verbose_name='Mahali'),
        ),
    ]
