# Generated by Django 6.1.1 on 2026-09-10 15:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0007_alter_listingfeerule_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('NEGOTIATING', 'Negotiating'), ('AGREED', 'Agreed'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='Hali')),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Bei iliyokubaliwa')),
                ('agreed_at', models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kukubaliana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_deal_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Mnunuzi')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_rooms', to='listings.listing', verbose_name='Tangazo')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_deal_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Muuzaji')),
            ],
            options={
                'db_table': 'deal_rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NegotiationOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kiasi cha offer')),
                ('message', models.TextField(blank=True, verbose_name='Ujumbe')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COUNTERED', 'Countered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Hali ya offer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
                ('deal_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='deals.dealroom', verbose_name='Deal Room')),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negotiation_offers', to=settings.AUTH_USER_MODEL, verbose_name='Aliyetoa offer')),
                ('responded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='deals.negotiationoffer', verbose_name='Offer iliyojibiwa')),
            ],
            options={
                'db_table': 'negotiation_offers',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dealroom',
            index=models.Index(fields=['seller', 'status'], name='deal_seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dealroom',
            index=models.Index(fields=['buyer', 'status'], name='deal_buyer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dealroom',
            index=models.Index(fields=['listing', 'status'], name='deal_listing_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dealroom',
            index=models.Index(fields=['status', 'updated_at'], name='deal_status_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='dealroom',
            constraint=models.UniqueConstraint(fields=('listing', 'buyer'), name='unique_deal_room_listing_buyer'),
        ),
        migrations.AddIndex(
            model_name='negotiationoffer',
            index=models.Index(fields=['deal_room', 'created_at'], name='offer_deal_created_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationoffer',
            index=models.Index(fields=['offered_by', 'created_at'], name='offer_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationoffer',
            index=models.Index(fields=['deal_room', 'status'], name='offer_deal_status_idx'),
        ),
    ]
