# Generated by Django 6.1.1 on 2026-09-28 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('listings', '0013_alter_listing_seller_alter_listingfee_listing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dealroom',
            name='unique_deal_room_listing_buyer',
        ),
        migrations.AddConstraint(
            model_name='dealroom',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'NEGOTIATING', 'AGREED'])), fields=('listing', 'buyer'), name='unique_active_deal_room_listing_buyer'),
        ),
    ]
