# Generated by Django 6.1.1 on 2026-10-06 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_remove_dealroom_unique_deal_room_listing_buyer_and_more'),
        ('listings', '0019_rename_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dealroom',
            name='unique_active_deal_room_listing_buyer',
        ),
        migrations.AlterField(
            model_name='dealroom',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('NEGOTIATING', 'Negotiating'), ('ACCEPTED', 'Accepted'), ('RESERVED', 'Reserved'), ('AWAITING_FINAL_PAYMENT', 'Awaiting final payment'), ('PAYMENT_PROOF_SUBMITTED', 'Payment proof submitted'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30, verbose_name='Hali'),
        ),
        migrations.AddConstraint(
            model_name='dealroom',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'NEGOTIATING', 'ACCEPTED'])), fields=('listing', 'buyer'), name='unique_active_deal_room_listing_buyer'),
        ),
    ]
