# Generated by Django 6.1.1 on 2026-10-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_remove_dealroom_unique_active_deal_room_listing_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiationoffer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COUNTERED', 'Countered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30, verbose_name='Hali ya offer'),
        ),
    ]
