# Generated by Django 6.1.1 on 2026-09-18 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_key', models.CharField(max_length=50, verbose_name='Huduma')),
                ('remaining', models.PositiveIntegerField(default=0, verbose_name='Zilizobaki')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Jumla')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Inaisha')),
                ('last_bundle_code', models.CharField(blank=True, max_length=100)),
                ('last_bundle_name', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL, verbose_name='Mtumiaji')),
            ],
            options={
                'verbose_name': 'Credit ya mtumiaji',
                'verbose_name_plural': 'Credits za watumiaji',
                'db_table': 'user_credits',
                'ordering': ['service_key'],
                'indexes': [models.Index(fields=['user', 'service_key'], name='uc_user_service_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'service_key'), name='uniq_user_credit_service')],
            },
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_key', models.CharField(max_length=50, verbose_name='Huduma')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Inaisha')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Mtumiaji')),
            ],
            options={
                'verbose_name': 'Huduma ya mtumiaji',
                'verbose_name_plural': 'Huduma za watumiaji',
                'db_table': 'user_services',
                'ordering': ['service_key'],
                'constraints': [models.UniqueConstraint(fields=('user', 'service_key'), name='uniq_user_service')],
            },
        ),
    ]
