# Generated by Django 6.1.1 on 2026-09-18 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Kitendo')),
                ('admin_name', models.CharField(blank=True, max_length=150, verbose_name='Jina la msimamizi')),
                ('target', models.CharField(blank=True, max_length=255, verbose_name='Kitu')),
                ('target_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID ya kitu')),
                ('details', models.TextField(blank=True, verbose_name='Maelezo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Msimamizi')),
            ],
            options={
                'verbose_name': 'Kumbukumbu ya kitendo',
                'verbose_name_plural': 'Kumbukumbu za matendo',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', 'created_at'], name='audit_admin_created_idx'), models.Index(fields=['action', 'created_at'], name='audit_action_created_idx')],
            },
        ),
    ]
