# Generated by Django 6.1.1 on 2026-09-18 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0009_listingfee_percentage_listingfee_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Bei wakati wa kuhifadhi')),
                ('snapshot_status', models.CharField(blank=True, max_length=30, verbose_name='Hali wakati wa kuhifadhi')),
                ('snapshot_title', models.CharField(blank=True, max_length=200, verbose_name='Jina wakati wa kuhifadhi')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Muda wa kuhifadhi')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.listing', verbose_name='Tangazo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL, verbose_name='Mtumiaji')),
            ],
            options={
                'verbose_name': 'Tangazo lililohifadhiwa',
                'verbose_name_plural': 'Matangazo yaliyohifadhiwa',
                'db_table': 'saved_listings',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', 'saved_at'], name='saved_user_time_idx'), models.Index(fields=['listing'], name='saved_listing_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'listing'), name='unique_saved_user_listing')],
            },
        ),
    ]
