# Generated by Django 6.1.1 on 2026-09-18 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0009_listingfee_percentage_listingfee_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Jina la utafutaji')),
                ('query', models.CharField(blank=True, max_length=255, verbose_name='Neno la utafutaji')),
                ('category_slug', models.CharField(blank=True, max_length=120, verbose_name='Slug ya kundi')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Mkoa')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Bei ya chini')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Bei ya juu')),
                ('verified_only', models.BooleanField(default=False, verbose_name='Zilizothibitishwa pekee')),
                ('match_count', models.PositiveIntegerField(default=0, verbose_name='Idadi ya match')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Ilipokaguliwa mwisho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL, verbose_name='Mtumiaji')),
            ],
            options={
                'verbose_name': 'Utafutaji uliosajiliwa',
                'verbose_name_plural': 'Utafutaji uliosajiliwa',
                'db_table': 'saved_searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearchMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_matches', to='listings.listing')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='searches.savedsearch')),
            ],
            options={
                'db_table': 'saved_search_matches',
                'ordering': ['-notified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['user', 'created_at'], name='ssearch_user_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedsearchmatch',
            constraint=models.UniqueConstraint(fields=('search', 'listing'), name='unique_search_listing_match'),
        ),
    ]
