# Generated by Django 6.1.1 on 2026-09-21 07:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('BANNER', 'Banner'), ('FEATURE', 'Feature'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('spent', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kampeni',
                'verbose_name_plural': 'Kampeni',
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
