# Generated by Django 6.1.1 on 2026-09-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerad',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bannerad',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='Hali ya malipo'),
        ),
    ]
