# Generated by Django 6.1.1 on 2026-10-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_banner_payment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerad',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
