# Generated by Django 6.1.1 on 2026-09-27 23:51

import apps.core.managers
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('boosting', '0001_initial'), ('boosting', '0002_alter_boostpackage_options_and_more'), ('boosting', '0003_alter_boostpackage_managers')]

    dependencies = [
        ('listings', '0007_alter_listingfeerule_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_hours', models.PositiveIntegerField(help_text='Muda wa boost kwa saa.', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Bei ya boost kwa TZS.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deletion_reason', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'boost_packages',
                'ordering': ['ordering', 'duration_hours', 'price'],
                'indexes': [models.Index(fields=['is_active', 'ordering'], name='boost_pkg_active_order_idx')],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListingBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boosts', to='listings.listing')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_boosts', to='boosting.boostpackage')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_boosts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listing_boosts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', 'status'], name='boost_listing_status_idx'), models.Index(fields=['seller', 'status'], name='boost_seller_status_idx'), models.Index(fields=['status', 'expires_at'], name='boost_status_exp_idx'), models.Index(fields=['payment_status', 'created_at'], name='boost_pay_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='boostpackage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_boost_package_name'),
        ),
        migrations.AlterModelManagers(
            name='boostpackage',
            managers=[
                ('objects', apps.core.managers.SoftDeleteManager()),
                ('all_objects', apps.core.managers.SoftDeleteManager(include_deleted=True)),
            ],
        ),
    ]
