# Generated by Django 6.1.1 on 2026-09-18 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0009_listingfee_percentage_listingfee_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=150)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Kiasi kilicholipwa')),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True, verbose_name='Hai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Inaisha')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_ads', to='listings.listing', verbose_name='Tangazo')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_ads', to=settings.AUTH_USER_MODEL, verbose_name='Muuzaji')),
            ],
            options={
                'verbose_name': 'Tangazo la banner',
                'verbose_name_plural': 'Matangazo ya banner',
                'db_table': 'banner_ads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['active', 'expires_at'], name='banner_active_exp_idx'), models.Index(fields=['seller', 'active'], name='banner_seller_active_idx')],
            },
        ),
    ]
