# Generated by Django 6.1.1 on 2026-10-08 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement_fees", "0003_remove_advertisementfeeconfig_days_and_more"),
        ("banners", "0004_alter_bannerad_payment_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannerad",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="banner_ads",
                to="advertisement_fees.advertisementpackage",
            ),
        ),
    ]
