# Generated by Django 6.1.1 on 2026-10-08 18:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0005_bannerad_package"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="title",
        ),
        migrations.AddField(
            model_name="campaign",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("BOOST", "Boost only"),
                    ("LEADING", "Leading only"),
                    ("ADVERTISEMENT", "Advertisement only"),
                    ("ALL", "All promotions"),
                ],
                default="ALL",
                help_text="Inatumika kwa aina gani ya promotions.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Punguzo kwa asilimia (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="name",
            field=models.JSONField(
                blank=True, default=dict, help_text="Jina la kampeni: {sw, en}"
            ),
        ),
        migrations.AlterField(
            model_name="bannerad",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Inaisha"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="description",
            field=models.JSONField(
                blank=True, default=dict, help_text="Maelezo: {sw, en}"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="type",
            field=models.CharField(
                choices=[
                    ("DISCOUNT", "Discount"),
                    ("BANNER", "Banner"),
                    ("FEATURE", "Feature"),
                    ("OTHER", "Other"),
                ],
                default="DISCOUNT",
                help_text="Legacy type (DISCOUNT/BANNER/FEATURE/OTHER).",
                max_length=20,
            ),
        ),
    ]
