# Generated by Django 6.1.1 on 2026-09-18 22:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('H24', '24 Hours'), ('H48', '48 Hours'), ('H72', '72 Hours'), ('CUSTOM', 'Custom (per day)')], max_length=10, unique=True)),
                ('hours', models.PositiveIntegerField(blank=True, help_text='Null for the custom tier.', null=True)),
                ('label_sw', models.CharField(max_length=100)),
                ('label_en', models.CharField(blank=True, max_length=100)),
                ('sub_sw', models.CharField(blank=True, max_length=100)),
                ('sub_en', models.CharField(blank=True, max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kiwango cha reservation',
                'verbose_name_plural': 'Viwango vya reservation',
                'db_table': 'reservation_rates',
                'ordering': ['ordering'],
            },
        ),
    ]
