# Generated by Django 6.1.1 on 2026-10-08 01:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_rates", "0002_change_to_flat_fee"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Kama False, reservation ni bure kwa tiers zote.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reservation Settings",
                "verbose_name_plural": "Reservation Settings",
                "db_table": "reservation_settings",
            },
        ),
        migrations.CreateModel(
            name="ReservationTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours",
                    models.PositiveIntegerField(
                        help_text="Muda wa reservation kwa masaa (mf. 12, 24, 168)."
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000"),
                        help_text="Bei ya tier kwa TZS.",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Kama False, tier haionekani kwenye dropdown.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Mpangilio wa kuonyesha (ndogo kwanza)."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reservation Tier",
                "verbose_name_plural": "Reservation Tiers",
                "db_table": "reservation_tier",
                "ordering": ["order", "hours"],
            },
        ),
        migrations.DeleteModel(
            name="ReservationRate",
        ),
        migrations.AddConstraint(
            model_name="reservationtier",
            constraint=models.UniqueConstraint(
                fields=("hours",), name="unique_reservation_tier_hours"
            ),
        ),
    ]
