# Generated by Django 6.1.1 on 2026-09-10 16:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        ('listings', '0007_alter_listingfeerule_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Bei iliyokubaliwa')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESERVATION_PENDING', 'Reservation Pending'), ('RESERVED', 'Reserved'), ('INSPECTION', 'Inspection'), ('READY_FOR_FINAL_PAYMENT', 'Ready for Final Payment'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=30, verbose_name='Hali ya muamala')),
                ('buyer_decision', models.CharField(choices=[('PENDING', 'Pending'), ('READY_FOR_FINAL_PAYMENT', 'Ready for Final Payment'), ('NOT_AS_DESCRIBED', 'Not as Described'), ('REQUEST_NEGOTIATION', 'Request Negotiation'), ('CANCEL_TRANSACTION', 'Cancel Transaction')], default='PENDING', max_length=30, verbose_name='Uamuzi wa mnunuzi')),
                ('buyer_decision_note', models.TextField(blank=True, verbose_name='Maelezo ya uamuzi wa mnunuzi')),
                ('buyer_decision_at', models.DateTimeField(blank=True, null=True, verbose_name='Muda wa uamuzi wa mnunuzi')),
                ('final_payment_proof', models.FileField(blank=True, null=True, upload_to='transactions/final-payment-proofs/', verbose_name='Ushahidi wa malipo ya mwisho')),
                ('final_payment_reference', models.CharField(blank=True, max_length=255, verbose_name='Reference ya malipo ya mwisho')),
                ('final_payment_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kupakia ushahidi')),
                ('seller_confirmed_payment', models.BooleanField(default=False, verbose_name='Muuzaji amethibitisha malipo')),
                ('seller_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Muda wa uthibitisho wa muuzaji')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kukamilika')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kughairiwa')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Sababu ya kughairi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Mnunuzi')),
                ('deal_room', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='deals.dealroom', verbose_name='Deal Room')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='listings.listing', verbose_name='Tangazo')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Muuzaji')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kiasi cha deposit')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='Hali ya malipo')),
                ('payment_reference', models.CharField(blank=True, max_length=255, verbose_name='Payment reference')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kulipa')),
                ('duration_hours', models.PositiveIntegerField(default=48, verbose_name='Muda wa reservation kwa saa')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Reservation inaanza')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Reservation inaisha')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING_PAYMENT', max_length=20, verbose_name='Hali ya reservation')),
                ('refund_reference', models.CharField(blank=True, max_length=255, verbose_name='Refund reference')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kurefund')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='transactions.transaction', verbose_name='Muamala')),
            ],
            options={
                'db_table': 'reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_hours', models.PositiveIntegerField(default=24, verbose_name='Muda wa inspection kwa saa')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Inspection inaanza')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Inspection inaisha')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Hali ya inspection')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Muda wa kukamilika')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Imesasishwa')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_period', to='transactions.transaction', verbose_name='Muamala')),
            ],
            options={
                'db_table': 'inspection_periods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer', 'status'], name='transaction_buyer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['seller', 'status'], name='transaction_seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['listing', 'status'], name='transaction_listing_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='transaction_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'expires_at'], name='reservation_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['payment_status', 'created_at'], name='res_pay_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionperiod',
            index=models.Index(fields=['status', 'expires_at'], name='inspection_status_exp_idx'),
        ),
    ]
