# Generated by Django 6.1.1 on 2026-10-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_reservation_res_payment_ref_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='buyer_decision',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY_FOR_FINAL_PAYMENT', 'Ready for Final Payment'), ('NOT_AS_DESCRIBED', 'Not as Described'), ('REQUEST_NEGOTIATION', 'Request Negotiation'), ('CANCEL_TRANSACTION', 'Cancel Transaction')], default='PENDING', max_length=40, verbose_name='Uamuzi wa mnunuzi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESERVATION_PENDING', 'Reservation Pending'), ('RESERVED', 'Reserved'), ('INSPECTION', 'Inspection'), ('READY_FOR_FINAL_PAYMENT', 'Ready for Final Payment'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], default='RESERVATION_PENDING', max_length=40, verbose_name='Hali ya muamala'),
        ),
    ]
