# Generated by Django 6.1.1 on 2026-09-17 20:54

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='notification',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('LISTING_CREATED', 'Listing Created'), ('LISTING_APPROVED', 'Listing Approved'), ('LISTING_REJECTED', 'Listing Rejected'), ('LISTING_DELETED', 'Listing Deleted'), ('LISTING_RESTORED', 'Listing Restored'), ('ACCOUNT_DELETED', 'Account Deleted'), ('ACCOUNT_RESTORED', 'Account Restored'), ('NEW_OFFER', 'New Offer'), ('OFFER_COUNTERED', 'Offer Countered'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('TRANSACTION_CREATED', 'Transaction Created'), ('RESERVATION_CREATED', 'Reservation Created'), ('RESERVATION_PAID', 'Reservation Paid'), ('RESERVATION_EXPIRING', 'Reservation Expiring'), ('RESERVATION_EXPIRED', 'Reservation Expired'), ('INSPECTION_STARTED', 'Inspection Started'), ('INSPECTION_COMPLETED', 'Inspection Completed'), ('BUYER_DECISION', 'Buyer Decision'), ('PAYMENT_PROOF_UPLOADED', 'Payment Proof Uploaded'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('TRANSACTION_COMPLETED', 'Transaction Completed'), ('TRANSACTION_CANCELLED', 'Transaction Cancelled'), ('WAITING_LIST_JOINED', 'Waiting List Joined'), ('WAITING_LIST_AVAILABLE', 'Waiting List Available'), ('BOOST_ACTIVATED', 'Boost Activated')], default='GENERAL', max_length=50, verbose_name='Aina ya arifa'),
        ),
    ]
