# Generated by Django 6.1.1 on 2026-09-20 15:32

import apps.core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notification',
            managers=[
                ('objects', apps.core.managers.SoftDeleteManager()),
                ('all_objects', apps.core.managers.SoftDeleteManager(include_deleted=True)),
            ],
        ),
    ]
