# Generated by Django 6.1.1 on 2026-10-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], db_index=True, default='user', max_length=10, verbose_name='Watazamaji'),
        ),
    ]
