# Generated by Django 5.1.15 on 2026-10-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('LISTING_CREATED', 'Listing Created'), ('LISTING_APPROVED', 'Listing Approved'), ('LISTING_REJECTED', 'Listing Rejected'), ('LISTING_DELETED', 'Listing Deleted'), ('LISTING_RESTORED', 'Listing Restored'), ('ACCOUNT_DELETED', 'Account Deleted'), ('ACCOUNT_RESTORED', 'Account Restored'), ('NEW_OFFER', 'New Offer'), ('OFFER_COUNTERED', 'Offer Countered'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('TRANSACTION_CREATED', 'Transaction Created'), ('RESERVATION_CREATED', 'Reservation Created'), ('RESERVATION_PAID', 'Reservation Paid'), ('RESERVATION_EXPIRING', 'Reservation Expiring'), ('RESERVATION_EXPIRED', 'Reservation Expired'), ('INSPECTION_STARTED', 'Inspection Started'), ('INSPECTION_COMPLETED', 'Inspection Completed'), ('BUYER_DECISION', 'Buyer Decision'), ('PAYMENT_PROOF_UPLOADED', 'Payment Proof Uploaded'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('TRANSACTION_COMPLETED', 'Transaction Completed'), ('DISPUTE_RESOLVED', 'Dispute Resolved'), ('TRANSACTION_CANCELLED', 'Transaction Cancelled'), ('WAITING_LIST_JOINED', 'Waiting List Joined'), ('WAITING_LIST_AVAILABLE', 'Waiting List Available'), ('BOOST_ACTIVATED', 'Boost Activated'), ('BOOST_PURCHASED', 'Boost Purchased'), ('LEADING_PURCHASED', 'Leading Purchased'), ('ADVERTISEMENT_PURCHASED', 'Advertisement Purchased'), ('BUNDLE_PURCHASED', 'Bundle Purchased'), ('LISTING_RELEASED', 'Listing Released'), ('MESSAGE_RECEIVED', 'Message Received'), ('VERIFICATION_REQUEST', 'Verification Request'), ('LISTING_FEE_PAID', 'Listing Fee Paid'), ('ACCOUNT_VERIFIED', 'Account Verified')], default='GENERAL', max_length=50, verbose_name='Aina ya arifa'),
        ),
    ]
